apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ykf1gxonl-go 
  janus-idp.io/tekton: ykf1gxonl-go
  backstage.io/kubernetes-id: ykf1gxonl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ykf1gxonl-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml